baseURL: https://ealen.fr
canonifyURLs: true

languageCode: en-us
title: "Ealen's Blog"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 2

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Site parameters
params:
  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/ealenn/ealenn
  gitBranch: master

  background: /images/site/background.webp
  logo:
    main: /images/site/main-logo.webp
    inverted: /images/site/inverted-logo.webp
    favicon: /images/site/favicon.png

  enableBlogPost: true
  enableTOC: true
  showFlags: true

  features:
    blog:
      enable: true
    notes:
      enable: true

  # Provide newsletter configuration. 
  # This feature has been implemented for Mailchimp only for now.
  # You can also hide it from the footer.
  newsletter:
    # specify whether you want to display the newsletter form 
    enable: false
    # specify which newsletter provider you want to use
    provider: mailchimp
    # specify the target URL for the subscription form
    mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=0&amp;id=0
