name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  publish-on-remote:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: ealen.fr
